# Exported from Render on 2024-11-18T13:38:02Z
services:
- type: web
  name: hw-sinatra-saas-wordguesser
  runtime: ruby
  repo: https://github.com/chang-wd/hw-sinatra-saas-wordguesser
  plan: free
  envVars:
  - key: PORT
    sync: false
  region: singapore
  buildCommand: bundle install
  startCommand: bundle exec rackup config.ru -p $PORT
version: "1"
